agv_driver_node:
  ros__parameters:
    agv_ip: "127.0.0.1"
    protocol_version: 1
    request_timeout_ms: 1000
    poll_interval_ms: 200
    cmd_vel_duration_ms: 200
    publish_tf: true
    stop_on_zero_cmd_vel: true
    map_frame_id: "map"
    base_frame_id: "base_link"
    enable_bootstrap: true
    enable_control_lock: false
    control_nick_name: "inspection_agv_driver"
    initial_map_name: ""
    auto_relocate: true
    skip_reloc_if_localized: true
    require_confirm_loc: false
    bootstrap_timeout_ms: 60000
    bootstrap_poll_interval_ms: 500
    bootstrap_retry_interval_ms: 5000
